version: '3.8'

services:
  map_bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    command: [ "node", "bot.js" ]
